// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenHTMLReport(arg1, arg2) {
  return window['go']['main']['App']['OpenHTMLReport'](arg1, arg2);
}

export function OpenResultsFolder() {
  return window['go']['main']['App']['OpenResultsFolder']();
}

export function RunRecon(arg1) {
  return window['go']['main']['App']['RunRecon'](arg1);
}
