// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSavedLeads() {
  return window['go']['main']['App']['ClearSavedLeads']();
}

export function ExportSavedLeadsCSV() {
  return window['go']['main']['App']['ExportSavedLeadsCSV']();
}

export function GetSavedLeads() {
  return window['go']['main']['App']['GetSavedLeads']();
}

export function OpenHTMLReport(arg1, arg2) {
  return window['go']['main']['App']['OpenHTMLReport'](arg1, arg2);
}

export function OpenResultsFolder() {
  return window['go']['main']['App']['OpenResultsFolder']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ParseCSVContent(arg1) {
  return window['go']['main']['App']['ParseCSVContent'](arg1);
}

export function RunBulkRecon(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunBulkRecon'](arg1, arg2, arg3);
}

export function RunRecon(arg1) {
  return window['go']['main']['App']['RunRecon'](arg1);
}

export function SaveGeneratedCSV(arg1) {
  return window['go']['main']['App']['SaveGeneratedCSV'](arg1);
}
