// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cache} from '../models';
import {bulk} from '../models';
import {main} from '../models';
import {models} from '../models';

export function ClearSavedLeads():Promise<void>;

export function ExportSavedLeadsCSV():Promise<string>;

export function GetSavedLeads():Promise<Array<cache.SavedLead>>;

export function OpenHTMLReport(arg1:string,arg2:string):Promise<void>;

export function OpenResultsFolder():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ParseCSVContent(arg1:string):Promise<Array<bulk.LeadTarget>>;

export function RunBulkRecon(arg1:Array<bulk.LeadTarget>,arg2:string,arg3:boolean):Promise<Array<bulk.EnrichedLeadExport>>;

export function RunRecon(arg1:main.ReconRequest):Promise<models.ReconResult>;

export function SaveGeneratedCSV(arg1:string):Promise<string>;
