// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function OpenHTMLReport(arg1:string,arg2:string):Promise<void>;

export function OpenResultsFolder():Promise<void>;

export function RunRecon(arg1:main.ReconRequest):Promise<models.ReconResult>;
